package com.globalxtreme.gxsales.helper.base

class DefaultResponse {
    val NO_INTERNET_CONNECTION = "No internet connection or can't connect to server"
    val ITEM_ALREADY_IN_LIST = "Item already in the list"
    val ITEM_QUANTITY_CANT_BE_0 = "Item quantity can't be 0"
    val ITEM_QUANTITY_EXCEED = "Quantity exceed item availability"
    val PLEASE_SIGN_CONTRACT = "Please sign the contract"
    val PLEASE_MAKE_CHANGE = "Please make a change"
    val PLEASE_SELECT_IMAGE = "Please select an image"
    val PLEASE_CREATE_PROFORMA_INVOICE = "Please create a proforma invoice"
    val PROFORMA_HAS_PAYMENT = "This proforma has payment already"
    val SURVEY_PHOTO_UPLOAD_SUCCESS = "Survey photo uploaded succesfully"
    val CONTRACT_UPLOAD_SUCCESS = "Contract uploaded successfuly"
    val PROSPECT_UPDATE_SUCCESS = "Prospect updated successfully"
    val PROSPECT_CREATE_SUCCESS = "Prospect created successfully"
    val DOWNLOAD_PDF_FAIL = "Failed to download PDF"
    val JUSTIFICATION_SUCCESS = "Justification successfully submitted for approval"
    val GENERAL_NOTES_SUCCESS = "General notes updated successfully"
    val GENERAL_NOTES_FAILED = "Failed to update General notes"
    val PLEASE_FILL_ALL_FORM = "Please fill all the form"
    val ERROR_FETCHING_FCM_TOKEN = "Error fetching FCM registration token"

    val EMAIL_NOT_VALID = "Please input a valid email"
    val PLEASE_ADD_EMAIL = "Please add an email"
    val EMAIL_CANT_EMPTY = "Email can't be empty"
    val PASSWORD_CANT_EMPTY = "Password can't be empty"
    val FIRST_NAME_CANT_EMPTY = "First name can't be empty"
    val LAST_NAME_CANT_EMPTY = "Last name can't be empty"
    val CELL_PHONE_CANT_EMPTY = "Cell phone number can't be empty"
    val COMPANY_NAME_CANT_EMPTY = "Company name can't be empty"
    val COMPANY_ADDRESS_CANT_EMPTY = "Company address can't be empty"
    val LOCATION_ADDRESS_CANT_EMPTY = "Location address can't be empty"
    val LATITUDE_CANT_EMPTY = "Latitude can't be empty"
    val LONGITUDE_CANT_EMPTY = "Longitude can't be empty"
    val PLEASE_SELECT_PACKAGE = "Please select package"
    val NOTES_CANT_EMPTY = "Notes can't be empty"
    val UPCOMING_FEATURE = "Upcoming Feature"
    val COPIED_TO_CLIPBOARD = "Copied to clipboard"

    val EMAIL_SENT = "Email sent"
    val EMAIL_SAVED_TO_DRAFT = "Email saved to draft"
    val EMAIL_CANCELED = "Email canceled"
    val EMAIL_FAILED = "Failed to sent email"

    val ATTENTION = "Attention"
    val WARNING = "Warning"
    val PENDING = "Pending"
    val SUCCESS = "Success"

    val SOMETHING_WENT_WRONG = "Something went wrong"
    val COULDNT_CONNECT_TO_SERVER = "Couldn't connect to server"
    val ERROR_400 = "Error Bad Request"
    val ERROR_401 = "You Are Unauthorized"
    val ERROR_404 = "Error Server Not Found"
    val ERROR_408 = "Request Timeout"
    val ERROR_413 = "Error Payload Too Large"
    val ERROR_422 = "Error Non-Processable Entity"
    val ERROR_429 = "Error Too Many Request"
    val ERROR_500 = "Internal Server Error"
    val ERROR_503 = "Service Unavailable"
    val ERROR_OCCURRED = "An Error Occurred"
}